apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
