apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
spec:
  type: NodePort
  selector:
    component: grafana
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP